apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hog
  labels:
    app: memory-hog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-hog
  template:
    metadata:
      labels:
        app: memory-hog
    spec:
      containers:
      - name: memory-hog
        image: polinux/stress
        resources:
          limits:
            memory: "50Mi"
          requests:
            memory: "20Mi"
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
